language: node_js
node_js: 8
sudo: false

install:
  - npm install
  - bundle install

script:
  - npm test

before_deploy:
  - travis_wait 30 npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash tools/bin/deploy.sh
  on:
    branch: master
