# =======
# Site settings
# =======
title:       Apache Cordova
description: Apache Cordova is a set of device APIs that allow a web mobile app developer to access native device function from JavaScript.
url:         "http://cordova.apache.org" # the base hostname & protocol
baseurl:     "" # the subpath of the site, e.g. /blog/
rss_path:    /feed.xml

excerpt_separator: <!--more-->
repo:
    uri:    https://github.com/apache/cordova-docs
    branch: cordova-website

# NOTE: defaults are configured in _defaults.yml, which is a generated file

# =======
# Build settings
# =======
source:      www
destination: build-dev

keep_files: [".git", ".svn", "wiki-images", "images", "downloads"]

lsi: false
safe: true
highlighter: pygments

markdown: kramdown
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

# exclude directories from the build
exclude:
    - static/css-src
